### ISSUE TITLE
Bug with applySIFT

### ISSUE THREAD

**Issue by TWANG006** [AntonioRedondo/ImageFeatureDetector#1]
Hi, 

This UI design is so impressed, but I just found a problem in the SIFT detector. Indeed, the number of octaves is decided by OpenCV itself based on the image's scale so the parameters used in the SIFT constructor should be SIFT::create(0, nOctaveLayers, threshold, edgeThreshold); This explains why your SIFT detector can detect much less key points than any other three less robust algorithm. Hope this helps. Thanks very much.

**Comment by AntonioRedondo** [comment]
Hello Twang!

Thank you for spotting the bug and opening the issue.

Antonio :)

**Comment by AntonioRedondo** [comment]
Hello @TWANG006,

For your info I just fixed this issue on commit https://github.com/AntonioRedondo/ImageFeatureDetector/commit/1b31a290c160e227564cf229fa85c93c7b3970de.
